// Generated by CoffeeScript 1.6.3
(function() {
  var Point, begin, border, borderColor, bug, canvas, d, draw, h, move, paused, reverse, run, runFor, runTime, toggle, velocity, w,
    _this = this;

  runTime = 5;

  w = 960;

  h = 500;

  d = 50;

  draw = SVG('canvas').size(w, h);

  border = draw.rect(w, h).attr({
    fill: "none",
    stroke: "#999",
    'stroke-width': 3
  });

  Point = (function() {
    function Point(x, y) {
      this.x = x;
      this.y = y;
    }

    return Point;

  })();

  velocity = new Point(5, 6);

  begin = new Point(d / 2, d, 2);

  bug = draw.circle(d).center(begin.x, begin.y).attr({
    id: "bug",
    fill: "aliceblue",
    stroke: "steelblue",
    'stroke-width': 5
  });

  borderColor = function(color) {
    return border.attr({
      stroke: color
    });
  };

  reverse = function() {
    borderColor("orange");
    setTimeout((function() {
      return borderColor("#999");
    }), 100);
    return -1;
  };

  move = function() {
    var x, y;
    x = bug.x();
    y = bug.y();
    if ((x + d > w) || (x < 0)) {
      velocity.x *= reverse();
    }
    if ((y + d > h) || (y < 0)) {
      velocity.y *= reverse();
    }
    return bug.move(x + velocity.x, y + velocity.y);
  };

  paused = false;

  toggle = function() {
    if (paused) {
      paused = false;
      return run();
    } else {
      return paused = true;
    }
  };

  canvas = document.getElementById("canvas");

  canvas.addEventListener('click', toggle);

  run = function() {
    move();
    if (paused) {
      return;
    }
    return requestAnimationFrame(run);
  };

  runFor = function(secs) {
    if (secs == null) {
      secs = 10;
    }
    setTimeout((function() {
      return paused = true;
    }), secs * 1000);
    return run();
  };

  runFor(runTime);

}).call(this);
