// Generated by CoffeeScript 1.6.3
(function() {
  var Extras, Point, Vector,
    __slice = [].slice;

  Point = (function() {
    function Point(x, y) {
      this.x = x;
      this.y = y;
    }

    return Point;

  })();

  Vector = (function() {
    function Vector(origin, end) {
      this.origin = origin;
      this.end = end;
    }

    return Vector;

  })();

  Extras = {
    vector: function(v, style) {
      var V;
      style || (style = {
        width: 3,
        opacity: .5,
        color: '#555'
      });
      V = this.line(v.origin.x, v.origin.y, v.end.x, v.end.y);
      V.color = function(color) {
        return V.stroke({
          'color': color
        });
      };
      return V.stroke(style);
    },
    bug: function(x, y, size) {
      var bug;
      if (x == null) {
        x = 0;
      }
      if (y == null) {
        y = 0;
      }
      if (size == null) {
        size = 20;
      }
      bug = this.circle(size).attr("id", "bug").cx(x).cy(y);
      bug.movesTo = function() {
        var V, chain;
        V = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        chain = function() {
          if (V.length) {
            return bug.moveTo(V.shift(), chain);
          }
        };
        return chain();
      };
      bug.moveTo = function(V, next) {
        return this.animate(2000, '-').center(V.x, V.y).after(next);
      };
      return bug;
    }
  };

  SVG.extend(SVG.Doc, Extras);

  window.Point = Point;

  window.Vector = Vector;

}).call(this);
