// Generated by CoffeeScript 1.6.3
(function() {
  var Engine, con, container, db, el, listen, multilevel, tn;

  container = require('container-el');

  multilevel = require('multilevel');

  Engine = require('engine.io-stream');

  db = multilevel.client();

  con = Engine('/engine');

  con.pipe(db.createRpcStream()).pipe(con);

  window.db = db;

  el = function(elem) {
    return document.createElement(elem);
  };

  tn = function(text) {
    return document.createTextNode(text);
  };

  listen = function(ch) {
    var msg, p;
    p = el(p);
    msg = ch.value.message;
    if (msg) {
      p.appendChild(tn(msg));
      return container.appendChild(p);
    }
  };

  db.createReadStream().on('data', listen);

}).call(this);
