// Generated by CoffeeScript 1.6.3
(function() {
  var Cursor, D2R, UnitCircle, deg2rad, extension,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  D2R = Math.PI / 180;

  deg2rad = function(d) {
    return d * D2R;
  };

  Cursor = (function() {
    function Cursor(x, y, draw) {
      this.x = x;
      this.y = y;
      this.draw = draw;
    }

    Cursor.prototype.lineTo = function(x, y, color) {
      if (color == null) {
        color = "steelblue";
      }
      this.draw.line(this.x, this.y, x, y).attr({
        stroke: color
      });
      this.x = x;
      this.y = y;
      return this;
    };

    Cursor.prototype.moveTo = function(x, y) {
      return this.lineTo(x, y, "none");
    };

    return Cursor;

  })();

  UnitCircle = (function(_super) {
    __extends(UnitCircle, _super);

    function UnitCircle(cx, cy, radius, draw) {
      this.cx = cx;
      this.cy = cy;
      this.radius = radius != null ? radius : 100;
      this.draw = draw;
      this.diameter = this.radius * 2;
      this.disc = this.draw.circle(this.diameter + 6).center(this.cx, this.cy);
      UnitCircle.__super__.constructor.call(this, this.cx, this.cy, this.draw);
    }

    UnitCircle.prototype._x = function(d) {
      return this.cx + Math.cos(deg2rad(-d)) * this.radius;
    };

    UnitCircle.prototype._y = function(d) {
      return this.cy + Math.sin(deg2rad(-d)) * this.radius;
    };

    UnitCircle.prototype.moveTo = function(deg) {
      this.lineTo(deg, "none");
      return this;
    };

    UnitCircle.prototype.lineTo = function(deg, color) {
      UnitCircle.__super__.lineTo.call(this, this._x(deg), this._y(deg), color);
      return this;
    };

    UnitCircle.prototype.markPoint = function(size) {
      if (size == null) {
        size = 10;
      }
      this.draw.circle(size).attr("class", "point").center(this.x, this.y);
      return this;
    };

    return UnitCircle;

  })(Cursor);

  extension = {
    unitCircle: function(x, y, r) {
      return new UnitCircle(x, y, r, this);
    }
  };

  SVG.extend(SVG.Doc, extension);

}).call(this);
