// Generated by CoffeeScript 1.6.3
(function() {
  var draw, drawn, erase, length, path, undo;

  path = document.querySelector('path');

  length = path.getTotalLength();

  path.style.transition = path.style.WebkitTransition = 'none';

  path.style.strokeDasharray = "" + length + " " + length;

  path.style.strokeDashoffset = length;

  path.getBoundingClientRect();

  path.style.transition = path.style.WebkitTransition = 'stroke-dashoffset 2s ease-in-out';

  drawn = false;

  draw = function() {
    drawn = true;
    path.style.strokeDasharray = length + ' ' + length;
    return path.style.strokeDashoffset = '0';
  };

  erase = function() {
    drawn = false;
    return path.style.strokeDashoffset = length - 20;
  };

  undo = function() {
    if (drawn) {
      return erase();
    } else {
      return draw();
    }
  };

  draw();

  path.addEventListener("webkitTransitionEnd", undo);

}).call(this);
